"""PrivateMeagges

Revision ID: 5da0b6858585
Revises: babc572a8302
Create Date: 2018-01-27 19:31:16.638382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da0b6858585'
down_revision = 'babc572a8302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_message_read_time')
    # ### end Alembic commands ###
