"""CleanUpUserModel

Revision ID: b00a582e7519
Revises: 5f9493d296a7
Create Date: 2018-01-31 05:24:25.313151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00a582e7519'
down_revision = '5f9493d296a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
