version: '3'

services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - postgres
      - elastic 

  postgres:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "P@ssw0rd!"
        POSTGRES_DB: "simpleblog"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
